# --------------------------------------------------
# Configuration for wall_seg project
# --------------------------------------------------

# --- Input Paths ---
data_folder: ./data/external/CubiCasa5k/data/cubicasa5k
train_file: ./data/external/CubiCasa5k/data/cubicasa5k/train.txt
val_file: ./data/external/CubiCasa5k/data/cubicasa5k/val.txt

# --- Processed Data Paths ---
# Used by preprocess.py (output) and train.py (input)
train_dest: ./data/processed/wall_seg/train
val_dest: ./data/processed/wall_seg/val

# --- Cache ---
hub_cache_dir: ./.torch_cache

# --- Preprocessing Parameters ---
preprocessing:
  preprocess_train: true
  max_train_images: 100 # No of images # Replace with -1 for full preprocessing
  preprocess_val: true
  max_val_images: 20
  
  crop_size: 512
  overlap: 64
  min_content_ratio: 0.1
  batch_size: 128  # Will auto-adjust based on available memory

# --- Training Parameters ---
training:
  epochs: 20
  # Training batch size
  batch_size: 16
  lr: 0.001
  momentum: 0.9
  num_workers: 1
  # Set to true to disable validation loop
  no_val: false


# --- Experiment Parameters ---
experiment:
  # Directory to save checkpoints
  exp_dir: ./experiments
  # Experiment name (if null, a timestamped name is generated)
  exp_name: wall_seg_nano

# --- Validation Parameters ---
# Used when running validate.py as a script
validation:
  # Number of samples to visualize
  num_samples: 5
  # Batch size for validation (1 is best for visualization)
  batch_size: 1